name: Build, Push and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: atique123/bookstore1:latest

    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "✅ Checking if Docker is installed..."
          if ! command -v docker &> /dev/null
          then
            echo "🚀 Docker not found, installing Docker..."
            sudo apt update
            sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt update
            sudo apt install -y docker-ce
            sudo systemctl start docker
            sudo systemctl enable docker
            echo "✅ Docker installed successfully!"
          else
            echo "✅ Docker is already installed!"
          fi

          echo "✅ Pulling latest Docker image from Docker Hub..."
          docker pull atique123/bookstore1:latest

          echo "✅ Stopping existing container if running..."
          docker stop bookstore-container || true
          docker rm bookstore-container || true

          echo "✅ Running new container..."
          docker run -d --name bookstore-container -p 80:80 atique123/bookstore1:latest

          echo "🎉 Deployment Finished Successfully!"
